### ISSUE TITLE
TASK frontend functionality to construct old conversation from backend data

### ISSUE THREAD

**Issue by williamirva** [APUOPE-RE/frontend#38]
Frontend has to construct old conversation when clicked old conversation is clicked.

- [ ] Create functionality to get conversation data from backend.
- [ ] Create functionality to construct conversation bubbles to UI based on data.

**Comment by roosavihlman** [comment]
After ticket https://github.com/orgs/APUOPE-RE/projects/3/views/1?pane=issue&itemId=83425778&issue=APUOPE-RE%7Cbackend%7C21 is merged, there is an endpoint `fetchAllConversations` under `/actions/chatbot.tsx` that returns all user's old conversations as a list. No parameters are needed to be passed since conversations are fetched for user with JWT.

I recommend to wait this merge, since then this old conversation fetching is fully done.
